#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := test

EXTRA_COMPONENT_DIRS := $(abspath ../bsp)

include $(IDF_PATH)/make/project.mk

